### ISSUE TITLE
Tree Structure Construction

### ISSUE THREAD

**Issue by zhenyuhe00** [CGCL-codes/HCB-pHCB#3]
Hi, I'm reproducing your method on the MIND-large dataset. I wonder if you could release the code for Tree Structure Construction. Thanks a lot!

**Comment by yusonghust** [comment]
You can just use the api: https://scikit-learn.org/stable/modules/generated/sklearn.cluster.MiniBatchKMeans.html#sklearn.cluster.MiniBatchKMeans to conduct clustering layer-by-layer. Since I have graduated, I may not be able to access the code on the server in my university.

**Comment by zhenyuhe00** [comment]
Thank you
